#!/bin/bash
set -ex
pacman -Syu --noconfirm --overwrite=*

cd /pkgs || exit 1
function build_package() {
  url=$1
  dir=$(basename "$url" | sed "s/\.git//")
  cat >"/build-$dir" <<EOF
#!/bin/bash
set -ex
hash -r
if [ ! -d $dir ]; then
  git clone --depth=1 $url $dir
else
  (
    cd $dir || exit 1
    git checkout .
    git reset --hard
    git pull
  )
fi
cd $dir
MAKEFLAGS=-j$(nproc --all) makepkg -s -f -A --noconfirm
EOF
  chmod a+x "/build-$dir"
  su alarm -s /bin/bash -c "/build-$dir"
}
function install_package() {
  pacman -U /pkgs/"$1"/*.pkg* --noconfirm --overwrite=*
}
function build_and_install_package() {
  build_package "$1"
  install_package "$(basename "$url" | sed "s/\.git//")"
}

# Make sure to uninstall pipewire to build kwin without pipewire
if pacman -Qs pipewire >/dev/null; then
  pacman -Rdd pipwire --noconfirm
fi

build_package "https://github.com/jld3103/alsa-ucm-beryllium.git" &
build_package "https://github.com/jld3103/ofono-qrtr.git" &
build_package "https://github.com/jld3103/kwin-git.git" &
build_and_install_package "https://aur.archlinux.org/qrtr-git.git"
build_and_install_package "https://aur.archlinux.org/qmic-git.git"
for url in \
  "https://aur.archlinux.org/tqftpserv-git.git" \
  "https://aur.archlinux.org/rmtfs-git.git" \
  "https://aur.archlinux.org/pd-mapper-git.git"; do
  build_package "$url" &
done
wait
