#!/bin/bash
set -ex

rm -rf /etc/resolv.conf
printf "nameserver 8.8.8.8\nnameserver 8.8.4.4" >/etc/resolv.conf
cat >/etc/pacman.conf <<EOF
[options]
HoldPkg = pacman glibc
Architecture = aarch64
Color
#CheckSpace
SigLevel = Never
LocalFileSigLevel = Optional

[plasma-mobile]
Server = file:///mnt/plasma-mobile

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

[alarm]
Include = /etc/pacman.d/mirrorlist

[aur]
Include = /etc/pacman.d/mirrorlist
EOF
sed -i 's/!ccache/ccache/' /etc/makepkg.conf

pacman-key --init
pacman-key --populate archlinuxarm
killall -KILL gpg-agent

pacman -Syy
pacman -Rns --noconfirm linux-aarch64
pacman -Su --noconfirm --overwrite=* --needed base-devel git ccache

usermod -a -G wheel alarm
sed -i "s/# %wheel ALL=(ALL) NOPASSWD: ALL/%wheel ALL=(ALL) NOPASSWD: ALL/" /etc/sudoers
chown alarm:alarm /home/alarm -R

mkdir -p /pkgs
chown alarm:alarm /pkgs -R
